[package]
name = "Modify_image_for_Rust"
version = "0.1.0"
authors = ["KodamaYuga <yk410320@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
